### ISSUE TITLE
Signing still broken. Also, retries fail if retry condition is not explicitly defined.

### ISSUE THREAD

**Issue by willvincent** [kndt84/aws-api-gateway-client#103]
Since other issues on the subject have been closed, despite still being an issue... 

Signing fails if retries are enabled, after v0.2.17

The cause of this, is that the alternate retry logic does not properly utilize the signed request payload, causing a signature mismatch.

My PR #102 resolves this, and additionally handles the scenario where retries are defined, but no retryCondition is defined in the config, which given it's 'optional' status should naturally fallback to utilize the default axios-retry condition -- which is does with this PR.

**Comment by kndt84** [comment]
Thanks for sending a PR. I've merged it.
