### ISSUE TITLE
Can I assign eslint and reformat code to reasonable syntax?

### ISSUE THREAD

**Issue by zeroasterisk** [kndt84/aws-api-gateway-client#11]
You've got spaces, tabs, and whatnot mixed in here. 

Can I assign a linter config and clean up the code?

It's hard to submit PRs without my linter being really angry.

> ✖ 545 problems (531 errors, 14 warnings)

**Comment by kndt84** [comment]
Of course, welcome! Please send pull request. I will merge the request.

**Comment by zeroasterisk** [comment]
So - this ended up being a huge PR - sorry.... need to kick the tires a bit before you merge... it *may* work...  I'll be trying it out too, later this week, but wanted to get it to you ASAP for review.

**Comment by kndt84** [comment]
Thanks for sending PR. I reviewed it. Though some modifications were needed, it works well.
