### ISSUE TITLE
Adding retry capability

### ISSUE THREAD

**Issue by kgorges** [kndt84/aws-api-gateway-client#20]
Has there been any thought to adding retry capability to the client. In particular, occasionally we get a 503 error returned from API gateway. This is a retriable error likely due to a transient error. It would be nice if we could specify retriable error conditions and counts. axios-retry could be used to configure axios with these parameters.

**Comment by kndt84** [comment]
Sorry for causing inconvenience. It was fixed with the following PR
#21
