### ISSUE TITLE
"service is not defined" errors after updating to v0.2.4

### ISSUE THREAD

**Issue by adambiggs** [kndt84/aws-api-gateway-client#22]
~After a quick review of the changes, it looks like [this line](https://github.com/kndt84/aws-api-gateway-client/blob/master/src/apigClient.js#L54) will never get hit, because `service` is defined as an empty string by default.~

Nevermind, it looks like the code is actually broken... Even adding `service` to our config object didn't fix the error. I just noticed [this comment](https://github.com/kndt84/aws-api-gateway-client/pull/18#commitcomment-22088013).

**Comment by adambiggs** [comment]
Could use a unit test 😉

**Comment by kndt84** [comment]
Sorry for causing inconvenience. It was fixed with the following PR
https://github.com/kndt84/aws-api-gateway-client/pull/21
