### ISSUE TITLE
Whenever i add make a post with a body amazon complains that the signature is invalid

### ISSUE THREAD

**Issue by l33way** [kndt84/aws-api-gateway-client#24]
I get:
The request signature we calculated does not match the signature you provided.

It works if i pass {} as the body.. but if i put anything else in.. like {"test":"test"} it fails.

**Comment by kndt84** [comment]
Can you paste error message?

**Comment by kndt84** [comment]
Recently, some updates are published. I hope they solve the issue. Please feel free to post a new issue if you face the same error.
