### ISSUE TITLE
Query Parameters with single quotes fails signature

### ISSUE THREAD

**Issue by kgorges** [kndt84/aws-api-gateway-client#25]
When passing a query parameter with a single quote, authorization fails. According to the latest SDK generated from one of my API gateway API's, the following function should be used in place of encodeURIIComponent:

function fixedEncodeURIComponent (str) {
      return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
        return '%' + c.charCodeAt(0).toString(16);
      });
    }

Single quotes should be escaped.

**Comment by kndt84** [comment]
Thanks for pointing out the single quotes failure. If you have enough time please send a PR. I willing to merge it.

**Comment by QChesthairQ** [comment]
hi, Takashi. Is this issue being fixed? I also encountered auth fails while passing  parameters with single quotes.

**Comment by kndt84** [comment]
Fixed!
