### ISSUE TITLE
Apigateway returns {"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by QChesthairQ** [kndt84/aws-api-gateway-client#29]
Hi, 
   I passed those three tokens in 
apigwClient = apigwClientFactory.newClient({
          accessKey: awsCredentails.accessKeyId,
          secretKey: awsCredentails.secretAccessKey,
          sessionToken: awsCredentails.sessionToken,
          invokeUrl: JSON.parse(awsmobile.aws_cloud_logic_custom)[0].endpoint
      });

with API gateway auth on with IAM, the API service can not load the data from dynamodb. Return a {"message":"Missing Authentication Token"}

**Comment by QChesthairQ** [comment]
Enabled CORS on API gateway side

**Comment by kndt84** [comment]
Have you checked the keys and the token are correct? This can be checked by using auto generated JavaScript SDK.

**Comment by QChesthairQ** [comment]
Thanks for replying:)
Currently the apiclient can work with IAM off in 'OPTIONS', IAM on in 'ANY'.
It seems does not pass the preflight check if 'OPTIONS' is on

**Comment by QChesthairQ** [comment]
The OPTIONS method will fail by passing those three tokens>.<

**Comment by kktam** [comment]
can someone create a sample project showing the exact configurations required?

**Comment by kndt84** [comment]
Have you checked the following page? This touches "Missing Authentication Token" error.
https://docs.aws.amazon.com/en_us/apigateway/latest/developerguide/amazon-api-gateway-using-stage-variables.html

**Comment by kndt84** [comment]
> The Invoke URL link points to the root resource of the API in its beta stage. Navigating to the URL by choosing the link calls the beta stage GET method on the root resource. If methods are defined on child resources and not on the root resource itself, choosing the Invoke URL link will return a {"message":"Missing Authentication Token"} error response. In this case, you must append the name of a specific child resource to the Invoke URL link.
