### ISSUE TITLE
Running on react-native causes TransformError

### ISSUE THREAD

**Issue by heyjared** [kndt84/aws-api-gateway-client#30]
```
TransformError: [omitted]/node_modules/aws-api-gateway-client/dist/apigClient.js: Unknown plugin "transform-es5-property-mutators" specified in "[omitted]/node_modules/aws-api-gateway-client/package.json" at 0, attempted to resolve relative to "[omitted]/node_modules/aws-api-gateway-client"

RCTFatal
-[RCTBatchedBridge stopLoadingWithError:]
__25-[RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0
```

Any ideas on how to get it working?

**Comment by chapeljuice** [comment]
I'm getting this too. Does anyone have any ideas? Or @heyjared did you fix this?

**Comment by heyjared** [comment]
I basically had to add the missing transforms or presets as devDependencies in my package.json.

For example in this case `transform-es5-property-mutators` was missing so I added the 
`babel-plugin-transform-es5-property-mutators` package.

**Comment by mk-nickyang** [comment]
I fixed this issue by remove
`  "babel": {
    "presets": [
      "@ava/stage-4",
      "es2017",
      "es2016",
      "es2015",
      "stage-0"
    ],
    "plugins": [
      "transform-es5-property-mutators"
    ]
  },
`
