### ISSUE TITLE
Couldn't catch error status codes 

### ISSUE THREAD

**Issue by kuldeep-surendra** [kndt84/aws-api-gateway-client#42]
Unable to catch the error status code, i could only catch error message as 'Network Error', Even though the console shows the status codes as 403(), 502()... I am unable to catch that.

**Comment by sam-jg** [comment]
@kuldeep-surendra I am having the same issue, did you find a solution?

**Comment by kuldeep-surendra** [comment]
@sam-jg , No I couldn't find the solution for that. Sometimes the error code comes and sometimes it dosen't.

**Comment by kndt84** [comment]
You can catch the response body in ```err.response.data```. Pls refer the following issue. https://github.com/kndt84/aws-api-gateway-client/issues/57
