### ISSUE TITLE
Fails to copy body when body is a Buffer

### ISSUE THREAD

**Issue by trocomocho** [kndt84/aws-api-gateway-client#44]
I've encountered this issue when trying to send an image as the body of the request.
The error I'm getting is:

buffer.js:208
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:208:11)
    at new Buffer (buffer.js:65:10)
    at Object.copy (.../node_modules/aws-api-gateway-client/dist/lib/apiGatewayCore/utils.js:71:20)
    at Object.simpleHttpClient.makeRequest (.../node_modules/aws-api-gateway-client/dist/lib/apiGatewayCore/simpleHttpClient.js:79:32)
    at Object.apiGatewayClient.makeRequest (.../node_modules/aws-api-gateway-client/dist/lib/apiGatewayCore/apiGatewayClient.js:67:24)
    at Object.apigClient.invokeApi (.../node_modules/aws-api-gateway-client/dist/apigClient.js:109:29)
    at .../tester.js:23:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Example: 

var apigClientFactory = require('aws-api-gateway-client').default;
var fs = require('fs');

var config = {
  invokeUrl:'## API Gateway ##',
  defaultContentType: 'image/jpeg',
  defaultAcceptType: 'application/json',
  region: '## AWS Region ##',
};
var apigClient = apigClientFactory.newClient(config);

fs.readFile('## Path to Image ##', function(err, data) {

  if (err) console.log(err);
  else {

    apigClient.invokeApi(
        {},
        {},
        'POST',
        { headers: { 'Content-Type': "image/jpeg"} },
        data
    )
    .then(function(result){
        console.log(result);
    }).catch( function(result){
        console.log(result);
    });

  }

});

Solution?:

Changing the code on utils.js copy method from:

  copy: function(obj) {
    if (null === obj || 'object' !== typeof obj) return obj;
    let copy = obj.constructor();
    let attr = null;
    for (attr in obj) {
      if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
    }
    return copy;
  }

to:

  copy: function copy(obj) {
    if (null == obj || 'object' != (typeof obj === 'undefined' ? 'undefined' : _typeof(obj))) return obj;
    if (Buffer.isBuffer(obj)) return Buffer.from(obj);
    var copy = obj.constructor();
    var attr = null;
    for (attr in obj) {
      if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
    }
    return copy;
  }

does work, now, I'm not Nodejs expert so I'm not sure is the best way of solving this.

Many thanks.

**Comment by zeroasterisk** [comment]
@trocomocho want to try my fork with just your 1 line change?
https://github.com/zeroasterisk/aws-api-gateway-client
it's now on PR #45 - please review there
