### ISSUE TITLE
 aws-api-gateway-client module usage behind an enterprise proxy

### ISSUE THREAD

**Issue by fredericE** [kndt84/aws-api-gateway-client#49]
Hello

I’m trying to use this module behind an enterprise proxy,  but 
Unfortunately I’m not able to find a way to do it

And I did not find any information in the documentation…
Thanks in advance for your help

Rgds
Fred

**Comment by zwik** [comment]
Having the same issue here. I'd like co configure the proxy and also something that not verify the SSL certificate. A flag similar to strict-ssl = false in NPM and --no-verify-ssl in aws-cli.

**Comment by kndt84** [comment]
This code automatically selects sigV4Client (IAM) or simpleHttpClient (apiKey), and the following lines relevant to this. If you comment out these lines, maybe it works behind the enterprise proxy.
https://github.com/kndt84/aws-api-gateway-client/blob/7d4e6fe1bce8ec92351472fdb867a82858970a00/src/lib/apiGatewayCore/apiGatewayClient.js#L50
