### ISSUE TITLE
headers/queryParams getting set to empty objects

### ISSUE THREAD

**Issue by mgarod** [kndt84/aws-api-gateway-client#5]
https://github.com/kndt84/aws-api-gateway-client/blob/master/apigClient.js#L96-L97
``` javascript
apigClient.invokeApi = function (params, pathTemplate, method, additionalParams, body) {
	if (additionalParams===undefined) additionalParams={};
	if (body===undefined) body='';
        
        var request = {
            verb: method.toUpperCase(),
            path: pathComponent + uritemplate.parse(pathTemplate).expand(params),
            headers: apiGateway.core.utils.parseParametersToObject(params, []), // here
            queryParams: apiGateway.core.utils.parseParametersToObject(params, []), // here
            body: body
        };
        
        return apiGatewayClient.makeRequest(request, authType, additionalParams, config.apiKey);
    };
```
``` javascript
parseParametersToObject: function (params, keys) {
        if (params === undefined) {
            return {};
        }
        var object = { };
        for (var i = 0; i < keys.length; i++) {
            object[keys[i]] = params[keys[i]];
        }
        return object;
    }
```

The AWS generated SDK would have hard coded the keys expected into those empty arrays. As this stands, I expect every request headers and queryParams to be set to {}.

Not sure what a solution would be, but I simple eliminated the use of parseParametersToObject, and passed the params directly since I knew the structure I was expecting in my API.

**Comment by kndt84** [comment]
Thanks for bringing up the issue. I understand that key list cannot be passed because it is hard coded as an empty array. Your solution, eliminating the use of parseParametersToObject, would be good, so I promise to update the code.

**Comment by mgarod** [comment]
I'll submit a pull request.

**Comment by kndt84** [comment]
In addition to correcting the code, please update README if possible.
