### ISSUE TITLE
Query Parameters not being passed to API

### ISSUE THREAD

**Issue by abhilashdk2016** [kndt84/aws-api-gateway-client#54]
Hi,

I have the below code to call an AWS API Endpoint that generates a random number between given min and max numbers. min and max are being passed to API as query parameters.

```
let AWS = require('aws-sdk');
AWS.config.loadFromPath('./config.json');
//AWS.config.region = 'ap-south-1';
let lambda = new AWS.Lambda();
let apigClientFactory = require('aws-api-gateway-client').default;
let config = {
    invokeUrl: 'https://abcdefgh.execute-api.ap-south-1.amazonaws.com/DEV',
    accessKey: '<access-key>',
    secretKey: '<secret-key>',
    region: 'ap-south-1'
};
let apigClient = apigClientFactory.newClient(config);
let apiParams = {min: 20,max: 40};
let body = {
    
}

let additionalParams = {
   
}
apigClient.invokeApi(apiParams, '/number', 'GET', additionalParams, body)
    .then(function (result) {
        console.log(result);
    })
    .catch(function (error) {
        console.log(error);
    });
```

Body mapping Template in API gateway for get method:

```
{
    "min" : $input.params('min'),
    "max" : $input.params('max')
}
```

But when I check Cloudwatch logs I see my query string parameters getting empty strings : 

`{ min: '', max: '' }`

So my lambda is returning null as the value.

Please let me know how to pass query strings to aws api.

Thanks in advance.

**Comment by abhilashdk2016** [comment]
I found the problem. I need to pass parameters in additionalParmaeters object like :

```
let additionalParams = {
   queryParams: {
   min: 20, max: 40
   }
}
```
But the text

```
var params = {
    //This is where any header, path, or querystring request params go. The key is the parameter named as defined in the API
    userId: '1234',
};
```
is misleading because query parameters were not passed ( maybe it was for me ).

Hope it helps.

**Comment by kndt84** [comment]
Good suggestion. I update README. Thx!

**Comment by abhilashdk2016** [comment]
Welcome :)
