### ISSUE TITLE
Error doesn't let you capture any response data

### ISSUE THREAD

**Issue by jtyler258** [kndt84/aws-api-gateway-client#57]
In our API we like to return information about errors especially 400 bad requests. For example:
`{
    "email": [
        "Missing data for required field."
    ]
}`

However, the error thrown seems to only contain the status code:
`Error: Request failed with status code 400`

Burying the response data on error makes it more tedious to troubleshoot errors during implementation. Could a second parameter be added to the error callback that contains the response?

**Comment by ffxsam** [comment]
We ran into this issue as well. The response body needs to be easily accessible at a higher level in the error object.

**Comment by ffxsam** [comment]
Upon further thought, I think the whole model of throwing an exception for a status 400 kinda doesn't work well. IMO it should always just return a response, and I can decide how to handle it, e.g.:

```js
const response = await apiClient.invokeApi(
  {},
  '/my/endpoint',
  'POST',
  {},
  payload
);

switch (response.status) {
  case 400:
    // ...
}
```

**Comment by ffxsam** [comment]
@jtyler258 aha. You'll want to look at `err.response.data` to get the response body.
