### ISSUE TITLE
Alternative to MobileHub?

### ISSUE THREAD

**Issue by ghost** [kndt84/aws-api-gateway-client#58]
Hello,

Sorry in advanced - I appreciate this isn't a direct issue but I'm new to AWS and I'm building both a mobile app and admin dashboard (React Native and React JS Respectively). 

Being new to AWS, I've noticed MobileHub but it seems that there's a great deal going on behind the scenes, and whilst attempting the MobileHub approach, I ended up implementing the various services independently all be it API Gateway, Lambda, and DynamoDB. 

So my question is does Amplify provide a means to interact with independently implemented Lambda functions i.e. not via MobileHub but via AWS Services? Or does Amplify only work with everything implemented via MobileHub?

The reason I ask is that there seems to be a number of guides out there for getting a mobile app started but they all seem to use MobileHub services rather than independently implemented services. 

I've tried various implementations of interfacing the react native app with AWS and in the future I would like to do the same for the react js dashboard. The working approach is the use of this library `aws-api-gateway-client` which works very well. 

`var apigClientFactory = require('aws-api-gateway-client').default;`

Having my Access key, secret key, endpoint, and api key each defined as `const`.

And then the following

```
apigClientFactoryConfig = { 
    invokeUrl : ENDPOINT,
    accessKey : ACCESS_KEY,
    secretKey : SECRET_KEY,
    region: 'eu-west-2',
    apiKey : API_KEY,
  }
var apigClient = apigClientFactory.newClient(apigClientFactoryConfig);
```

And then the following function

```
export async function getMenus() {
    // let apiName = 'Menus';
    // let path = '/';
    // let myInit = { // OPTIONAL
    //     headers: {} // OPTIONAL
    // }
    // return await API.get(apiName, path, myInit);

    console.log('getMenus');

    let response = null;

    var params = {
        //This is where any header, path, or querystring request params go. The key is the parameter named as defined in the API
        TableName: 'Menus',
    };
    // Template syntax follows url-template https://www.npmjs.com/package/url-template
    var pathTemplate = '/Development/menus/'
    var method = 'GET';
    var additionalParams = {
        //If there are any unmodeled query parameters or headers that need to be sent with the request you can add them here
        headers: {
            param0: '',
            param1: ''
        },
        queryParams: {
          TableName: 'Menus'
        }
    };
    var body = {
        //This is where you define the body of the request
    };
  
    return await apigClient.invokeApi(params, pathTemplate, method, additionalParams, body)
    .then(function(result){
    // console.log('result', result.data);
        return result;
        //This is where you would put a success callback
    }).catch( function(result){
    // console.log('result', result);
        //This is where you would put an error callback
        return result;
    });
    return false;
}
```

_The commented out code represents use of `aws-amplify` `api` and `storage` _

_The query provides a means to `GET` data from a giving path where `development` is my deployed `API Gateway` and `menus` is the desired resource.

_Please note the method implemented isn't finalized here, its just an initial example to illustrate_

And with this in mind, how do I initialize `aws-api-gateway-client` but for the entire application? 

```
apigClientFactoryConfig = { 
    invokeUrl : ENDPOINT,
    accessKey : ACCESS_KEY,
    secretKey : SECRET_KEY,
    region: 'eu-west-2',
    apiKey : API_KEY,
  }
var apigClient = apigClientFactory.newClient(apigClientFactoryConfig);
```

Currently the initialising lies inside my API functions class where I make my various `API` calls but I expect its better to perform this initalization in the main component `App.js`? Please do correct me if I'm wrong.

I guess further questions would be
- Do I need to or can I make `Amplify` and `aws-api-gateway-client` work together particularly from a credentials and authentication point of view?
- Why would you implement using the `MobileHub` approach when you can implement the services individually? Other than perhaps being quicker and project based?

Other libraries reviewed were the `aws-sdk` such as

`aws-sdk/dist/aws-sdk-react-native`
and 
`var APIGateway = require('aws-sdk/clients/apigateway');`

where again something such as 

```
    var myConfig = new AWS.Config({
      credentials: credentials, region: 'eu-west-2'
    });

    console.log('myconfig', myConfig);

    var apigateway = new AWS.APIGateway();
```

will follow.

Thank you for your help and support - I'm trying to get the best start to AWS but I'm a bit confused between the various libraries and approaches to interfacing a mobile app and dashboard with the AWS Services such as Lambda, DynamoDB, and API Gateway.

**Comment by kndt84** [comment]
I'm not familiar with Amplify, so I cannot answer the question.
