### ISSUE TITLE
npm modul not found

### ISSUE THREAD

**Issue by MarcelZOI** [kndt84/aws-api-gateway-client#61]
Hey guys,

if I want to use aws-api-gateway-client in react-native i get this error:
`Unknown plugin "transform-es5-property-mutators" specified in "/Users/marcel/Desktop/Allgaier/allgaier_app/node_modules/aws-api-gateway-client/package.json"`
and if i remove that line in the package.json i get the next error:
`Unknown npm modul "@ava/stage-4" specified in "/Users/marcel/Desktop/Allgaier/allgaier_app/node_modules/aws-api-gateway-client/package.json"`

Any ideas?

version: 0.2.14 (latest)

**Comment by kndt84** [comment]
Did you install devDependencies packages? It should work if these packages correctly work.
