### ISSUE TITLE
Request for HTTPS resource fails with SSL23_GET_SERVER_HELLO:unknown protocol when an HTTPS_PROXY has been configured in HTTPS over HTTP mode

### ISSUE THREAD

**Issue by aregier** [kndt84/aws-api-gateway-client#67]
Error: write EPROTO 140735491711808:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:825:

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite (net.js:867:14)

Steps to reproduce:
* Run a nodeJS process with the following environment variable set:
HTTPS_PROXY=http://proxyServer:port

```javascript
// This is a sample request that doesn't even use IAM authentication.
const apigClient = apigClientFactory.newClient({
    accessKey: '',
    invokeUrl: 'https://abcdefghij.execute-api.us-east-1.amazon.com/stage',
    region,
    secretKey: ''
});
const response = apigClient.invokeApi({}, '/api/something', 'GET', {}, {});
```

I've tested the same request through the new axios pre-release and it works:
```javascript
const response = await axios.get('https://abcdefghij.execute-api.us-east-1.amazon.com/stage/api/something', {});
```

**Comment by aregier** [comment]
Here is a record of the merged PR in axios that fixes this issue: https://github.com/axios/axios/pull/959

We want to be able to support consuming AWS apis through a proxy server, so integrating this fix from axios would be much appreciated.

**Comment by kndt84** [comment]
I've updated axios.
