### ISSUE TITLE
When the latest changes will be getting published to npm. The commit is 29eb2cd25742a77d489a8d427f6a2b918d3b9f0

### ISSUE THREAD

**Issue by manishsbd** [kndt84/aws-api-gateway-client#72]
Hi
 
     I had make some changes to the util.js file related to the buffer. which is already been merged. The commit is 429eb2cd25742a77d489a8d427f6a2b918d3b9f0. I just wanted to know, when the changes will be releasing to npm. It will resolve our problem of mentioning it every time.

Thanks & Regards
Manish Rana

**Comment by kndt84** [comment]
Sorry for replying late. I've just published.
