### ISSUE TITLE
buildCanonicalHeaders should lowercase header names before sorting 

### ISSUE THREAD

**Issue by eranation** [kndt84/aws-api-gateway-client#77]
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

To create the canonical headers list, convert all header names to lowercase and remove leading spaces and trailing spaces. Convert sequential spaces in the header value to a single space.

I think that right now it sorts first, lower case later.

**Comment by kndt84** [comment]
Thansk for sendig a PR
