### ISSUE TITLE
queryParams aren't working since v0.3.0

### ISSUE THREAD

**Issue by adambiggs** [kndt84/aws-api-gateway-client#85]
It looks like the `mergeInto()` util function broke. I think it has something to do with this change:

https://github.com/kndt84/aws-api-gateway-client/commit/6cd90e287ded7bd254dbc7bea2d18a5bcb9008cc#diff-e39402a30fcb608161d4646025526642

**Comment by kndt84** [comment]
Okay, I'll check later
