### ISSUE TITLE
Issue with '@babel/runtime/helpers/interopRequireDefault'

### ISSUE THREAD

**Issue by MatthewGan923** [kndt84/aws-api-gateway-client#90]
When execute: 
`var apigClientFactory = require('aws-api-gateway-client').default;`
i get the error message: 
'Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault''
It looks like a version compatibility issue. Should I downgrade any module?

**Comment by hobsons-feliperoque** [comment]
I was having the same issue with this, the solution was to run this in the importing project:
`npm install --save-dev @babel/runtime`

But that `@babel/runtime` is already defined as a `devDependency` in the [package.json](https://github.com/kndt84/aws-api-gateway-client/blob/master/package.json).
As per [the docs](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file), `devDependencies` are not made available to external packages.

The way I found to avoid adding `@babel/runtime` to the importing project was to fork this repo and move `@babel/runtime` from a `devDependency` to a normal dependency.

@kndt84, what do you think about this? Should the same be done in the original repo?

**Comment by medington** [comment]
Why is this issue closed with no resolution? Certainly still appears broken on master. `@babel/runtime` needs to be a `dependency` as it's used at runtime.
